<?php

namespace Fetchtex\FAQs\Model\ResourceModel;

use Magento\Framework\Model\ResourceModel\Db\AbstractDb;

class Faq extends AbstractDb
{

    protected function _construct()
    {
        $this->_init("fetchtex_faq","entity_id");
    }

    public function delete( \Magento\Framework\Model\AbstractModel $object )
    {
        return parent::delete($object); // TODO: Change the autogenerated stub
    }
}